version: "3.8"
networks:
  sherlock_net:
    external: false

services:
  sdk:
    image: mcr.microsoft.com/dotnet/sdk:6.0
    volumes:
      - .:/opt/app
    working_dir: /opt/app
    
  runtime:
    image: mcr.microsoft.com/dotnet/runtime:6.0
    volumes:
      - ./.output:/opt/app
    working_dir: /opt/app
    command:
      - dotnet
      - Sherlock.App.dll
      - "${ARGS}"
    